# Generated by Django 5.0.3 on 2024-04-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.CharField(max_length=4)),
                ('naam', models.CharField(max_length=264)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataMaand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maand', models.CharField(choices=[('Januarie', 'Januarie'), ('Februarie', 'Februarie'), ('Maart', 'Maart'), ('April', 'April'), ('Mei', 'Mei'), ('Junie', 'Junie'), ('Julie', 'Julie'), ('Augustus', 'Augustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=20, null=True)),
                ('jaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.kpa')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('maand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.datamaand')),
                ('kpa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.kpa', verbose_name='KPA')),
            ],
        ),
    ]
