# Generated by Django 5.0.3 on 2024-04-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='begin',
            field=models.IntegerField(default=0),
        ),
    ]
